# Importing the libraries

In [ ]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

# Loading the dataset

In [ ]:
df = pd.read_csv('/Users/priyashaprasad/Documents/Summer Analytics Course/SLR/salaries.csv')

In [3]:
df.head()

company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

# Splitting the label from the dataset to variable y

In [14]:
y = df['salary_more_then_100k']

In [15]:
y.head()

0    0
1    0
2    1
3    1
4    0
Name: salary_more_then_100k, dtype: int64

In [6]:
inputs = df.drop('salary_more_then_100k',axis='columns')

In [7]:
inputs.head()

company                  job     degree
0  google      sales executive  bachelors
1  google      sales executive    masters
2  google     business manager  bachelors
3  google     business manager    masters
4  google  computer programmer  bachelors

# Encoding of categorical variables

In [8]:
from sklearn.preprocessing import LabelEncoder
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

In [9]:
inputs['company_n'] = le_company.fit_transform(inputs['company'])
inputs['job_n'] = le_job.fit_transform(inputs['job'])
inputs['degree_n'] = le_degree.fit_transform(inputs['degree'])

In [35]:
inputs

company                  job     degree  company_n  job_n  degree_n
0       google      sales executive  bachelors          2      2         0
1       google      sales executive    masters          2      2         1
2       google     business manager  bachelors          2      0         0
3       google     business manager    masters          2      0         1
4       google  computer programmer  bachelors          2      1         0
5       google  computer programmer    masters          2      1         1
6   abc pharma      sales executive    masters          0      2         1
7   abc pharma  computer programmer  bachelors          0      1         0
8   abc pharma     business manager  bachelors          0      0         0
9   abc pharma     business manager    masters          0      0         1
10    facebook      sales executive  bachelors          1      2         0
11    facebook      sales executive    masters          1      2         1
12    facebook     business manager  bachelors          1      0         0
13    facebook     business manager    masters          1      0         1
14    facebook  computer programmer  bachelors          1      1         0
15    facebook  computer programmer    masters          1      1         1

# Dropping the normal columns to have only encoded inputs

In [16]:
X = inputs.drop(['company','job','degree'],axis='columns')

In [17]:
X.head()

company_n  job_n  degree_n
0          2      2         0
1          2      2         1
2          2      0         0
3          2      0         1
4          2      1         0

# Train Test Split

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [22]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(12, 3)
(4, 3)
(12,)
(4,)


# Importing the classifier

In [23]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

# Fitting the values of the training set

In [24]:
model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

# Predicting the test data

In [27]:
y_pred = model.predict(X_test)

# Accuracy of the training set

In [25]:
model.score(X_train,y_train)

1.0

# Accuracy of the test set

In [26]:
model.score(X_test,y_test)

0.75

# Comparing the actual values and predicted values

In [28]:
comparison = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
comparison.head()

Actual  Predicted
14       1          1
4        0          1
12       1          1
3        1          1

# Predicting values - when passed as individual lists

Is salary of Google, Computer Engineer, Bachelors degree > 100 k ?

In [29]:
model.predict([[2,1,0]])

array([1])

Is salary of Google, Computer Engineer, Masters degree > 100 k ?

In [31]:
model.predict([[2,1,1]])

array([1])

Is salary of ABC Pharma, Sales Executive, Bachelors degree > 100 k ?

In [37]:
model.predict([[0,2,0]])

array([0])